### ISSUE TITLE
fill all the necessary information in README.md

### ISSUE THREAD

**Issue by Arsenic-ATG** [Arsenic-ATG/8085#42]
current readme doesn't provide any information about using the project or even building it. 
of course this would not be the final product but would prove to be a strong foundation to make the project public and then work on it publicly with other possible contributors online.

- [x] Add installation instructions to the README.md
- [x] Add contribution guidelines to the README.md
- [x] Complete the *feedback* section of the README.md
- [x] Fill the license section of the README.md
